# suppressWarnings(library(shiny))
# setwd("C:/Users/jlee/Documents/Data Science/Data Products/LTV")

shinyUI(
  pageWithSidebar(
    # Application title
    headerPanel("Lifetime Value Predictor"),
    sidebarPanel(
      h1('LTV Inputs'),
      h4('Enter data about members acquired in a given quarter:'),
      radioButtons("type","Cohort Type:", c("Marketing" = "mkt","Organic" = "org"), inline = TRUE),
      numericInput("members", '# of Members Acquired', 300000, min = 0),
      numericInput("netrev", 'Net Revenues (generated by cohort in initial quarter):', 442000, min = 0),
      numericInput("pct", '% of Full Year Revenues', 43, min = 0),
      numericInput("discount", 'Discount Rate (%):', 16, min = 0),
      submitButton('Submit')
    ),
    mainPanel(
      h2('Output'),
      h4('Lifetime Value:'),
      verbatimTextOutput("ltv_pred"),
      h4('Present Value of Lifetime Value:'),
      verbatimTextOutput("ltvpv_pred"),
      plotOutput("plot"),
      h2('Key Inputs'),
      h4('A key input into the LTV calculation is the net revenues generated by the cohort in the first quarter of signup.'),
      h4('Net Revenue Per Signup in 1st Quarter:'),
      verbatimTextOutput("netpermember"),

      h2('Background and Motivation'),
      h4('Your marketing team spends millions of dollars on various online campaigns to drive users to your website and signup new members.  But is the marketing spend worthwhile?  You need to know the lifetime value (LTV) of new members!'), 
      h4('This App predicts the LTV of new member cohorts.  LTV is the sum of future cash flows, projected forward on an exponentially declining basis, which is based on the historical cohort performance of past cohorts.  The exponential rates are different between members acquired organically versus thiose from marketing sources.  These expontial rates are built into the forecasting model and drive the cashflow projections shown above.')
    )
  )
)
